language: ruby
rvm:
  - 1.9.3
before_script:
  - mysql -e 'create database congress_forms_test;'
  - cp config/database-example.rb config/database.rb
  - "PADRINO_ENV=test rake ar:create"
script: rake spec
